animal:
  num: 2
  x_interval: [500, 1400]
  y_interval: [100, 900]

robot:
  num: 1
  id: 10
  x_interval: [300, 310]
  y_interval: [150, 850]
  pos:
    - [350, 250]
    - [350, 400]
    - [350, 550]
    - [350, 700]
  sensing_range: 300.0
  comms_range: 200.0
  max_v: 10.0
  max_a: 20.0
