animal:
  num: 2
  x_interval: [500, 700]
  y_interval: [400, 500]

robot:
  num: 1
  id: 10
  x_interval: [300, 310]
  y_interval: [150, 850]
  sensing_range: 200.0
  comms_range: 200.0
  max_v: 100.0
  max_a: 20.0
